name: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Set up .env
      run: cp .env.example .env

    - name: Generate Laravel app key
      run: php artisan key:generate

    - name: Configure database
      run: |
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=testing/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env

    - name: Run migrations
      run: php artisan migrate

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xzf apache-jmeter-5.6.2.tgz

    - name: Run JMeter Tests
      run: |
        ./apache-jmeter-5.6.2/bin/jmeter -n -t ./jmeter/TestCI.jmx -l results.jtl -e -o report

    - name: Check Test Results
      run: |
        echo "Analyzing JMeter results..."
        error_rate=$(grep -c "false" results.jtl || true)
        total_requests=$(wc -l < results.jtl)
        if [ $error_rate -gt 0 ]; then
          echo "Error rate is too high: $error_rate failed requests out of $total_requests"
          exit 1
        fi

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: |
          results.jtl
          report/

 